# Generated by Django 4.0 on 2022-01-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('dorm', models.CharField(choices=[('K', 'Kissam'), ('E', 'EBI'), ('Z', 'Zeppos'), ('Ro', 'Rothschild'), ('Ra', 'Rand'), ('B', 'Branscomb'), ('H', 'Highland'), ('C', 'Commons'), ('V', 'Village')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm', models.CharField(choices=[('K', 'Kissam'), ('E', 'EBI'), ('Z', 'Zeppos'), ('Ro', 'Rothschild'), ('Ra', 'Rand'), ('B', 'Branscomb'), ('H', 'Highland'), ('C', 'Commons'), ('V', 'Village')], max_length=1)),
                ('number', models.IntegerField()),
                ('student_using', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='project_sundays.student')),
                ('students_reserving', models.ManyToManyField(blank=True, default=None, to='project_sundays.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Dryer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm', models.CharField(choices=[('K', 'Kissam'), ('E', 'EBI'), ('Z', 'Zeppos'), ('Ro', 'Rothschild'), ('Ra', 'Rand'), ('B', 'Branscomb'), ('H', 'Highland'), ('C', 'Commons'), ('V', 'Village')], max_length=1)),
                ('number', models.IntegerField()),
                ('student_using', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='project_sundays.student')),
                ('students_reserving', models.ManyToManyField(blank=True, default=None, to='project_sundays.Student')),
            ],
        ),
    ]
