# Generated by Django 4.0 on 2022-01-12 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_sundays', '0003_alter_washer_student_using_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryer',
            name='dorm',
            field=models.CharField(choices=[('K', 'Kissam'), ('E', 'EBI'), ('Z', 'Zeppos'), ('Ro', 'Rothschild'), ('Ra', 'Rand'), ('B', 'Branscomb'), ('H', 'Highland'), ('C', 'Commons'), ('V', 'Village')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dryer',
            name='student_using',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_dryer_user', to='project_sundays.student'),
        ),
        migrations.AlterField(
            model_name='dryer',
            name='students_reserving',
            field=models.ManyToManyField(default=None, null=True, related_name='students_reserving_dryer', to='project_sundays.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dorm',
            field=models.CharField(choices=[('K', 'Kissam'), ('E', 'EBI'), ('Z', 'Zeppos'), ('Ro', 'Rothschild'), ('Ra', 'Rand'), ('B', 'Branscomb'), ('H', 'Highland'), ('C', 'Commons'), ('V', 'Village')], max_length=50),
        ),
        migrations.AlterField(
            model_name='washer',
            name='dorm',
            field=models.CharField(choices=[('K', 'Kissam'), ('E', 'EBI'), ('Z', 'Zeppos'), ('Ro', 'Rothschild'), ('Ra', 'Rand'), ('B', 'Branscomb'), ('H', 'Highland'), ('C', 'Commons'), ('V', 'Village')], max_length=50),
        ),
        migrations.AlterField(
            model_name='washer',
            name='student_using',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_washer_user', to='project_sundays.student'),
        ),
        migrations.AlterField(
            model_name='washer',
            name='students_reserving',
            field=models.ManyToManyField(default=None, null=True, related_name='students_reserving_washer', to='project_sundays.Student'),
        ),
    ]
